spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernates:
        format_sql:true
        generate_statistics:true
  datasource:
    url: jdbc:mysql://localhost:27306/hooing
    username: svr
    password: vmfkdzm2!@#
server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: cldi2248
    key-store-type: PKCS12
    key-alias: bns-ssl
